/*
 * Generated by the RESOLVE to C translator. This file
 * should not be modified.
 */
#ifndef __ARRAY_REALIZ_H
#define __ARRAY_REALIZ_H

#include "../../../RESOLVE.h"
#include "../../../Main/Concepts/Stack_Template/Stack_Template.h"
#include "../../../Main/Facilities/Standard/Std_Boolean_Fac.h"
#include "../../../Main/Facilities/Standard/Std_Integer_Fac.h"

extern Stack_Template* new_Array_Realiz_for_Stack_Template(type_info* Entry, r_type_ptr Max_Depth);
extern void free_Array_Realiz_for_Stack_Template(Stack_Template* toFree);

#endif