/*
 * Generated by the RESOLVE to C translator. This file
 * should not be modified.
 */
#include "Array_Realiz.h"

typedef struct _Contents_Array_Fac_1 _Contents_Array_Fac_1;
struct _Contents_Array_Fac_1 {
    Static_Array_Template* core;
};

typedef struct Realization_Specific Realization_Specific;
struct Realization_Specific {
    _Contents_Array_Fac_1 _Contents_Array_Fac_1_Var;
};

typedef struct Stack_Instance Stack_Instance;
struct Stack_Instance {
    r_type_ptr Contents;
    r_type_ptr Top;
};

static r_type_ptr createStack(type_info* StackType) {
    Stack_Template* this = StackType->PointerToFacility;
    Stack_Instance* Stack_i = calloc(1, sizeof(Stack_Instance));

    _Contents_Array_Fac_1 _Contents_Array_Fac_1_Var = ((Realization_Specific*)
        this->Realization_Specific)->_Contents_Array_Fac_1_Var;

    Stack_i->Contents = _Contents_Array_Fac_1_Var.core->Static_Array->create(_Contents_Array_Fac_1_Var.core->Static_Array); 
    Stack_i->Top = Std_Integer_Fac_Var.core->Integer->create(Std_Integer_Fac_Var.core->Integer); 
    Stack_Instance** t = malloc(sizeof(Stack_Instance*));

    *t = si;
    return (r_type_ptr)t;
}

static void destroyStack(r_type_ptr r, type_info* StackType) {
    Stack_Instance* Stack_i = *r;
    Stack_Template* this = StackType->PointerToFacility;

    _Contents_Array_Fac_1 _Contents_Array_Fac_1_Var = ((Realization_Specific*)
            this->Realization_Specific)->_Contents_Array_Fac_1_Var;

    _Contents_Array_Fac_1_Var.core->Static_Array->destroy(Stack_i->Contents,
        _Contents_Array_Fac_1_Var.core->Static_Array); 
    Std_Integer_Fac_Var.core->Integer->destroy(Stack_i->Top,
        Std_Integer_Fac_Var.core->Integer); 
    free(*r);
    free(r);
}
static void Pop(r_type_ptr R, r_type_ptr S, Stack_Template* this) {
    Stack_Instance* _SI = *S;


}

static r_type_ptr Rem_Capacity(r_type_ptr S, Stack_Template* this) {
    Stack_Instance* _SI = *S;

    r_type_ptr Rem_Capacity = Std_Integer_Fac_Var.core->Integer->create(Std_Integer_Fac_Var.core->Integer);

	return Rem_Capacity;
}

extern Stack_Template* new_Array_Realiz_for_Stack_Template(type_info* Entry, r_type_ptr Max_Depth) {
    Stack_Template* this = calloc(1, sizeof(Stack_Template));
    this->Pop = Pop;
    this->Rem_Capacity = Rem_Capacity;
    this->Entry = Entry;
    this->Max_Depth = Std_Integer_Fac_Var.core->Replica(Max_Depth);

    type_info* Stack_i = calloc(1, sizeof(type_info));
    Stack_i->create = createStack;
    Stack_i->destroy = destroyStack;
    this->Stack = Stack_i;
    this->Stack->PointerToFacility = this;

    Realization_Specific* temp = calloc(1, sizeof(Realization_Specific));
    temp->_Contents_Array_Fac_1_Var.core = new_Std_Array_Realiz_for_Static_Array_Template();
    this->Realization_Specific = temp;
}

extern void free_Array_Realiz_for_Stack_Template(Stack_Template* toFree) {

    free(toFree->Stack);
}