/*
 * Generated by the RESOLVE to C translator. This file
 * should not be modified.
 */
#ifndef __STACK_TEMPLATE_H
#define __STACK_TEMPLATE_H

#include "../../../RESOLVE.h"
#include "../../../Main/Facilities/Standard/Std_Boolean_Fac.h"
#include "../../../Main/Facilities/Standard/Std_Integer_Fac.h"

typedef struct Stack_Template Stack_Template;
struct Stack_Template {
    void* Realization_Specific;
    type_info* Stack;
    void (*Push) (r_type_ptr, r_type_ptr, Stack_Template*);
    void (*Pop) (r_type_ptr, r_type_ptr, Stack_Template*);
    r_type_ptr (*Depth) (r_type_ptr, Stack_Template*);
    r_type_ptr (*Rem_Capacity) (r_type_ptr, Stack_Template*);
    void (*Clear) (r_type_ptr, Stack_Template*);
};
#endif