/*
 * Generated by the RESOLVE to C translator. This file
 * should not be modified.
 */
#include "Int_Do_Nothing_Exercise.h"

void Int_Do_Nothing_Exercise_create() {
	Std_Boolean_Fac_create();
	Std_Integer_Fac_create();
}

void Int_Do_Nothing_Exercise_destroy() {
    Std_Boolean_Fac_destroy();
    Std_Integer_Fac_destroy();
}

void Do_Nothing(r_type_ptr I) {

}

void Main() {
	r_type_ptr X = Std_Integer_Fac_Var.core->Integer->create(Std_Integer_Fac_Var.core->Integer);

}

int main() {
    Int_Do_Nothing_Exercise_create();
    Main();
    Int_Do_Nothing_Exercise_destroy();
    return 0;
}