/*
 * Generated by the RESOLVE to C translator. This file
 * should not be modified.
 */
#ifndef __INT_DO_NOTHING_EXERCISE_H
#define __INT_DO_NOTHING_EXERCISE_H

#include "../../../RESOLVE.h"
//#include "../../../Main/Concepts/Standard/Static_Array_Template/Static_Array_Template.h"
//#include "../../../Main/Concepts/Standard/Location_Linking_Template_1/Location_Linking_Template_1.h"
#include "../../../Main/Facilities/Standard/Std_Boolean_Fac.h"
#include "../../../Main/Facilities/Standard/Std_Integer_Fac.h"

void Int_Do_Nothing_Exercise_create();
void Int_Do_Nothing_Exercise_destroy();

#endif