/*
 * Generated by the RESOLVE to C translator. This file
 * should not be modified.
 */
#include "Alt_Rev_Stack.h"

void Alt_Rev_Stack_create() {
	Std_Boolean_Fac_create();
	Std_Integer_Fac_create();
    Stack_Fac.core = new_Array_Realiz_for_Stack_Template();
    Stack_Fac.Writing_Capability = new_Obvious_Writing_Realiz_for_Writing_Capability_for_Stack_Template(Stack_Fac.core);
    Stack_Fac.Reading_Capability = new_Obvious_Reading_Realiz_for_Reading_Capability_for_Stack_Template(Stack_Fac.core);
}

void Alt_Rev_Stack_destroy() {
    free_Array_Realiz_for_Stack_Template(Stack_Fac.core);
    free(Stack_Fac.Writing_Capability);
    free(Stack_Fac.Reading_Capability);
    Std_Boolean_Fac_destroy();
    Std_Integer_Fac_destroy();
}

void Main() {
	r_type_ptr S1 = Stack_Fac.core->Stack->create(Stack_Fac.core->Stack);
	r_type_ptr S2 = Stack_Fac.core->Stack->create(Stack_Fac.core->Stack);

	Stack_Fac.core->Stack->destroy(S1, Stack_Fac.core->Stack); 
	Stack_Fac.core->Stack->destroy(S2, Stack_Fac.core->Stack); 
}

int main() {
    Alt_Rev_Stack_create();
    Main();
    Alt_Rev_Stack_destroy();
    return 0;
}