/*
 * Generated by the RESOLVE to C translator. This file
 * should not be modified.
 */
#ifndef __LEDS_TEST_H
#define __LEDS_TEST_H

#include "../../../RESOLVE.h"
#include "../../../Main/Facilities/Standard/Std_Boolean_Fac.h"
#include "../../../Main/Facilities/Standard/Std_Integer_Fac.h"
#include "../../../Main/Facilities/Standard/Std_Clock_Fac.h"
#include "../../../Main/Concepts/Leds_Template/Leds_Template.h"
#include "../../../Main/Concepts/Leds_Template/Std_Leds_Realiz.h"
#include "../../../Main/Concepts/Leds_Template/Toggling_Realiz.h"

typedef struct Led_Facility Led_Facility;
struct Led_Facility {
    Leds_Template* core;
	Toggling_Capability_for_Leds_Template* Toggling_Capability;
};
Led_Facility Led_Facility_Var;
void Leds_Test_create();
void Leds_Test_destroy();

#endif
