/*
 * Generated by the RESOLVE to C translator. This file
 * should not be modified.
 */
#ifndef __BOOLEAN_TEMPLATE_H
#define __BOOLEAN_TEMPLATE_H

#include "../../../../RESOLVE.h"

typedef struct Boolean_Template Boolean_Template;
struct Boolean_Template {
    void* Realization_Specific;
    type_info* Boolean;
    r_type_ptr (*True) (Boolean_Template*);
    r_type_ptr (*False) (Boolean_Template*);
    r_type_ptr (*And) (r_type_ptr, r_type_ptr, Boolean_Template*);
    r_type_ptr (*Or) (r_type_ptr, r_type_ptr, Boolean_Template*);
    r_type_ptr (*Not) (r_type_ptr, Boolean_Template*);
    r_type_ptr (*Are_Equal) (r_type_ptr, r_type_ptr, Boolean_Template*);
    r_type_ptr (*Are_Not_Equal) (r_type_ptr, r_type_ptr, Boolean_Template*);
    r_type_ptr (*Replica) (r_type_ptr, Boolean_Template*);
	void (*assign) (r_type_ptr, r_type_ptr, Boolean_Template*);
	void (*Read) (r_type_ptr, Boolean_Template*);
    void (*Write) (r_type_ptr, Boolean_Template*);
    void (*Write_Line) (r_type_ptr, Boolean_Template*);
    r_type_ptr (*createFromBoolean) (int, type_info*);
	r_type_ptr (*createBoolean) (type_info*);
};
#endif
