/*
 * Generated by the RESOLVE to C translator. This file
 * should not be modified.
 */
#ifndef __STD_CLOCK_FAC_H
#define __STD_CLOCK_FAC_H

#include "../../../RESOLVE.h"
#include "../../../Main/Facilities/Standard/Std_Boolean_Fac.h"
#include "../../../Main/Facilities/Standard/Std_Integer_Fac.h"
#include "../../../Main/Concepts/Clock_Template/Clock_Template.h"
#include "../../../Main/Concepts/Clock_Template/Std_Clock_Realiz.h"

typedef struct Std_Clock_Fac Std_Clock_Fac;
struct Std_Clock_Fac {
    Clock_Template* core;
};
Std_Clock_Fac Std_Clock_Fac_Var;
void Std_Clock_Fac_create();
void Std_Clock_Fac_destroy();

#endif
