/*
 * Generated by the RESOLVE to C translator. This file
 * should not be modified.
 */
#ifndef __CLOCK_TEMPLATE_H
#define __CLOCK_TEMPLATE_H

#include "../../../RESOLVE.h"
#include "../../../Main/Facilities/Standard/Std_Boolean_Fac.h"
#include "../../../Main/Facilities/Standard/Std_Integer_Fac.h"

typedef struct Clock_Template Clock_Template;
struct Clock_Template {
    void* Realization_Specific;
    void (*Wait_1_Second) (Clock_Template*);
    void (*Wait_5_Seconds) (Clock_Template*);
    void (*Wait_500_Milli_Seconds) (Clock_Template*);
};
#endif