/*
 * Generated by the RESOLVE to C translator. This file
 * should not be modified.
 */
#ifndef __STD_CLOCK_REALIZ_H
#define __STD_CLOCK_REALIZ_H

#include "Clock_Template.h"

extern Clock_Template* new_Std_Clock_Realiz_for_Clock_Template();
extern void free_Std_Clock_Realiz_for_Clock_Template(Clock_Template* toFree);

#endif
