/*
 * Generated by the RESOLVE to C translator. This file
 * should not be modified.
 */
#include "Std_Clock_Realiz.h"
#include "Clock_Template.h"
#ifdef TELOS
#include <msp430.h>
#include <legacymsp430.h>
#endif

extern void free_Std_Clock_Realiz_for_Clock_Template(Clock_Template* toFree) {
	sfree(toFree);
}

static void Wait_1_Second(Clock_Template* this) {
#ifdef TELOS
	__delay_cycles(40000000);	
#else
	printf("Waiting 1 Second...\n");
#endif
}

static void Wait_5_Seconds(Clock_Template* this) {
#ifdef TELOS
	__delay_cycles(20000000);
#else
	printf("Waiting 5 Seconds...\n");
#endif
}

static void Wait_500_Milli_Seconds(Clock_Template* this) {
#ifdef TELOS
	__delay_cycles(2000000);
#else
	printf("Waiting 500 Milliseconds...\n");
#endif
}

extern Clock_Template* new_Std_Clock_Realiz_for_Clock_Template() {
	Clock_Template* this = salloc(sizeof(Clock_Template));
	this->Wait_5_Seconds = Wait_5_Seconds;
	this->Wait_1_Second = Wait_1_Second;
	this->Wait_500_Milli_Seconds = Wait_500_Milli_Seconds;

	return this;	
}
