/*
 * Generated by the RESOLVE to C translator. This file
 * should not be modified.
 */
#ifndef __LEDS_TEMPLATE_H
#define __LEDS_TEMPLATE_H

#include "../../../RESOLVE.h"
#include "../../../Main/Facilities/Standard/Std_Boolean_Fac.h"
#include "../../../Main/Facilities/Standard/Std_Integer_Fac.h"

typedef struct Leds_Template Leds_Template;
struct Leds_Template {
    r_type_ptr Strip_Length;
    void* Realization_Specific;
    type_info* Led;
    void (*Set) (r_type_ptr, r_type_ptr, r_type_ptr, Leds_Template*);
    r_type_ptr (*Status) (r_type_ptr, r_type_ptr, Leds_Template*);
    r_type_ptr (*Length) (r_type_ptr, Leds_Template*);
};
#endif