/*
 * Generated by the RESOLVE to C translator. This file
 * should not be modified.
 */
#ifndef __TOGGLING_CAPABILITY_H
#define __TOGGLING_CAPABILITY_H

#include "../../../RESOLVE.h"
#include "../../../Main/Concepts/Leds_Template/Leds_Template.h"
#include "../../../Main/Facilities/Standard/Std_Boolean_Fac.h"
#include "../../../Main/Facilities/Standard/Std_Integer_Fac.h"

typedef struct Toggling_Capability_for_Leds_Template Toggling_Capability_for_Leds_Template;
struct Toggling_Capability_for_Leds_Template {
    Leds_Template* core;
    void* Realization_Specific;
    void (*Toggle) (r_type_ptr, r_type_ptr, Toggling_Capability_for_Leds_Template*);
};
#endif
