/*
 *  * Generated by the RESOLVE to C translator. This file
 *   * should not be modified.
 *    */
#ifndef __TOGGLING_REALIZ_H
#define __TOGGLING_REALIZ_H

#include "../../../RESOLVE.h"
#include "../../../Main/Concepts/Leds_Template/Leds_Template.h"
#include "../../../Main/Concepts/Leds_Template/Toggling_Capability.h"
#include "../../../Main/Facilities/Standard/Std_Boolean_Fac.h"
#include "../../../Main/Facilities/Standard/Std_Integer_Fac.h"

extern Toggling_Capability_for_Leds_Template*
new_Toggling_Realiz_for_Toggling_Capability_of_Leds_Template(Leds_Template*);

#endif
